# Generated by Django 3.2 on 2022-05-22 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_user_book_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_book_rate',
            name='rate',
        ),
        migrations.AddField(
            model_name='user_book_rate',
            name='book_views',
            field=models.IntegerField(default=0),
        ),
    ]
