# Generated by Django 3.2 on 2022-06-07 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('library_app', '0007_chapter_chapter_visible'),
        ('user_app', '0007_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookStatusUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_app.book')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.book_status')),
            ],
        ),
    ]
