# Generated by Django 3.2 on 2022-06-07 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_bookstatususer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookstatususer',
            options={'verbose_name': 'Статус', 'verbose_name_plural': 'Статусы'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
