# Generated by Django 3.2 on 2022-06-13 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0009_auto_20220607_2131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookstatususer',
            options={'verbose_name': 'Статус пользователя', 'verbose_name_plural': 'Статусы пользователя'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='creation_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
