# Generated by Django 3.2 on 2021-12-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_auto_20211220_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
