# Generated by Django 3.2 on 2022-05-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0004_alter_book_book_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_visible',
            field=models.BooleanField(default=False),
        ),
    ]
