# Generated by Django 3.2 on 2022-06-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0006_chapter_chapter_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='chapter_visible',
            field=models.BooleanField(default=False),
        ),
    ]
